#!/bin/bash
# ---------------------------------------------------------------------------
# render-caddy-compose.sh — regenerate /home/deploy/caddy/docker-compose.yml
# on a server, listing every Swarm overlay network the local Caddy needs to
# attach to. Idempotent — runs `docker compose up -d` ONLY if the rendered
# file changed (so deploys that don't add a new overlay are no-ops).
#
# WHY THIS EXISTS:
# Before this script, scripts/ci/deploy-app.sh used `docker network connect
# caddy <overlay>` to attach Caddy to each new project's overlay. That
# attachment does NOT survive a Caddy container restart (compose recreate,
# host reboot, kernel update). The 2026-05-03 incident: kernel-update
# reboot on all 3 Hetzner hosts dropped Caddy on rishi-2, restart wiped
# overlay attachments → ~14% of Cloudflare probes returned 521 for ~8h
# until manual fix.
#
# HOW IT FIXES IT:
# Declares each overlay in the compose file with `external: true`. Compose
# auto-attaches Caddy to every listed overlay on every `up -d`, persistent
# across restarts and reboots.
#
# HOW THIS SCRIPT WORKS:
#   1. Read /home/deploy/caddy/.overlays-list (one overlay name per line).
#   2. Render docker-compose.yml from a heredoc, listing every overlay
#      under both `services.caddy.networks` and the top-level `networks`
#      block (with `external: true`).
#   3. If the rendered file differs from the existing one, swap it in
#      atomically and run `docker compose up -d` to recreate Caddy with
#      the new network attachments. If unchanged, skip — no recreate.
#
# CALLED BY:
#   - scripts/ci/update-caddy.sh (on every deploy, after the snippet is
#     written, after appending the project's overlay to .overlays-list)
#   - scripts/add-server.sh (on initial server provisioning, with a
#     baseline empty overlay list — Caddy starts with just `web`)
#   - manually by ops, e.g. after recovering Caddy from a corrupt state
#
# ENV VARS (all optional, with sensible defaults):
#   CADDY_DIR — defaults to /home/deploy/caddy
#   CADDY_INCLUDE_WEB_BRIDGE — set to "false" on hosts that do NOT run any
#     local app container (e.g. rishi-3 today). Defaults to "true". On a
#     Caddy-only host, the local `web` bridge has nothing to proxy to so
#     skipping it removes a noisy "network not found" path. Note: even when
#     "false", if the `web` bridge does not exist on the host, the compose
#     up will still fail because `external: true` requires existence — the
#     setting is a hint, not a guarantee.
# ---------------------------------------------------------------------------

# Stop on first error so a failed `docker compose up` halts the script
# instead of silently leaving Caddy in a broken state.
set -e

CADDY_DIR="${CADDY_DIR:-/home/deploy/caddy}"
OVERLAYS_FILE="${CADDY_DIR}/.overlays-list"
COMPOSE_FILE="${CADDY_DIR}/docker-compose.yml"
COMPOSE_TMP="${COMPOSE_FILE}.new"
INCLUDE_WEB="${CADDY_INCLUDE_WEB_BRIDGE:-true}"

# Make sure the caddy dir + overlay list exist (first-run bootstrap).
mkdir -p "${CADDY_DIR}"
touch "${OVERLAYS_FILE}"

# Build the YAML fragments for service networks + top-level external decls.
# We start with the local `web` bridge (only on hosts that run app
# containers), then append every overlay from .overlays-list.
SERVICE_NETWORKS=""
NETWORK_DECLS=""

if [ "${INCLUDE_WEB}" = "true" ]; then
    SERVICE_NETWORKS="      - web"
    NETWORK_DECLS="  web:
    external: true"
fi

# Append each overlay (sorted + deduped so output is stable across runs).
# Skip blank lines and comment lines starting with #.
while IFS= read -r overlay; do
    [ -z "${overlay}" ] && continue
    [[ "${overlay}" =~ ^# ]] && continue
    SERVICE_NETWORKS="${SERVICE_NETWORKS}${SERVICE_NETWORKS:+
}      - ${overlay}"
    NETWORK_DECLS="${NETWORK_DECLS}${NETWORK_DECLS:+
}  ${overlay}:
    external: true"
done < <(sort -u "${OVERLAYS_FILE}")

# Render the compose file. Heredoc so all the YAML lives in one place
# and is grep-able. The leading comment in the rendered file tells any
# future ops engineer not to edit it by hand — the source of truth is
# .overlays-list, not the YAML.
cat > "${COMPOSE_TMP}" <<COMPOSE
# Generated by caddy/render-caddy-compose.sh — DO NOT EDIT BY HAND.
# Source list of overlay networks: ${OVERLAYS_FILE}
# Edit that file (or let scripts/ci/update-caddy.sh manage it), then
# re-run this script to regenerate.
services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./conf.d:/etc/caddy/conf.d:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
${SERVICE_NETWORKS}

networks:
${NETWORK_DECLS}

volumes:
  caddy_data:
  caddy_config:
COMPOSE

# Atomic swap — only restart Caddy if the rendered compose actually changed.
# `cmp -s` returns 0 if files are identical, so we negate to detect change.
if [ -f "${COMPOSE_FILE}" ] && cmp -s "${COMPOSE_TMP}" "${COMPOSE_FILE}"; then
    rm -f "${COMPOSE_TMP}"
    echo "    caddy compose unchanged — no restart"
else
    mv "${COMPOSE_TMP}" "${COMPOSE_FILE}"
    echo "    caddy compose changed — applying via docker compose up -d"
    cd "${CADDY_DIR}"
    docker compose up -d
fi
